global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'streamxr'
    static_configs:
      - targets: ['streamxr:3000']
        labels:
          service: 'streamxr'
